### ISSUE TITLE
Use `reverse_commit_list()` in more places

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/git#1156]
From https://lore.kernel.org/git/CABPp-BESAh6wLComJoYsf7Q7NF2EMPptKRhfAoy=1-ZRZovnaQ@mail.gmail.com/:

> [...] we could also [... use `reverse_commit_list()` in ...] the code snippets in `builtin/merge.c` and `sequencer.c` that you can find with
>
> ```shell
> git grep commit_list_insert.*reversed
> ```

**Comment by victorphoenix3** [comment]
Hi, I am new to the community. May I submit a patch for this issue?

**Comment by dscho** [comment]
Yes! You don't even need anyone's permission for that :grin:

**Comment by newren** [comment]
This was implemented last year (see thread at https://lore.kernel.org/git/CANsrJQd0v2V9H8HPkiH2179C1c-NOSTRRB8YXt8v6R0YAbFPDQ@mail.gmail.com).

Closing now.
