### ISSUE TITLE
unable to create temporary file: Operation not permitted

### ISSUE THREAD

**Issue by aixi88** [gitgitgadget/git#1204]
Debian GNU/Linux 11 (bullseye)
git version 2.30.2
git root is virtualbox shared folder
git init  is OK,but git add error
```
zz@osboxes:~/projects/zzoo/v14$ git add .
error: unable to create temporary file: Operation not permitted
error: .devcontainer/Dockerfile: failed to insert into database
error: unable to index file '.devcontainer/Dockerfile'
```

**Comment by dscho** [comment]
@aixi88 please note that we use this issue tracker only as an informal way to track project ideas, the Git project does not use GitHub for bug tracking. See https://git-scm.com/community#bug-reporting how to report bugs to the Git project.
