### ISSUE TITLE
Should the commit message check 'fail' for long `lore.kernel.org` links

### ISSUE THREAD

**Issue by PhilipOakley** [gitgitgadget/git#1283]
in my `[gitgitgadget/git] Add some Glossary terms, and extra `renormalize` information. (PR #1282)`
series, the GGG CI check fails with
```
There are issues in commit https://github.com/gitgitgadget/git/commit/8fefb4936e143793c9ddbfc074c63cff1d65bc6a:
doc add: renormalize is not idempotent for CRCRLF
Lines in the body of the commit messages should be wrapped between 60 and 76 characters.
```
where the only long line is the link to the bug report that triggered the doc change.

Is it possible to detect and ignore such long lines, maybe with a 12 char allowance for "bug report: " before the link?

**Comment by dscho** [comment]
We already accept long lines that start with white space, and long lines that have no white space to break at. Isn't that enough? You could put that URL on its own line, after all, no need to make the line longer than necessary.

Also: wouldn't gitgitgadget/gitgitgadget be the correct place for this ticket (it's not about Git at all, which is however gitgitgadget/git's scope).

**Comment by PhilipOakley** [comment]
> We already accept long lines that start with white space, and long lines that have no white space to break at. Isn't that enough? You could put that URL on its own line, after all, no need to make the line longer than necessary.

I wasn't aware of those particular 'rules', however in this case the link is vast 108 characters long (that's Outlook for you;-). It did feel right to prefix the link with the "Bug report", which wasn't picked up when I had the series in Git-for-Windows, so it was a surprise failure when rebased across to GitGitGadget. 

Anyway it looks like it's passed CI checks now, so all good so far.

**Comment by PhilipOakley** [comment]
> wouldn't gitgitgadget/gitgitgadget be the correct place for this ticket (it's not about Git at all, which is however gitgitgadget/git's scope

I think that's a user experience (UX) confusion. It simply didn't occur to me at the time that there was another place to report the problem. 

It maybe that an "Issue Template" for gitgitgadget/git (ggg/git) would help in guiding folks as to how to decide if their problem fell on the side of being a ggg/git issue, or more in ggg/ggg's scope. It would have helped me.

Thanks.

**Comment by PhilipOakley** [comment]
> Anyway it looks like it's passed CI checks now, so all good so far.

I spoke too soon. That was just the CI check, not the ggg line length check that had passed. My `/submit` generated a repeat failure.

One thought is that the error message could be updated to include the two caveats you stated above, so as to cover indented text (i.e. those with that leading space), and the very long single 'word'/URL style cases. That should help folks avoid fretting about how to "get past" the gitgitgadget bot checks.

If I understand correctly the ggg-bot is actually hosted separately, so I wasn't able to see where such a change would be applied.

**Comment by dscho** [comment]
> One thought is that the error message could be updated to include the two caveats you stated above, so as to cover indented text (i.e. those with that leading space), and the very long single 'word'/URL style cases. That should help folks avoid fretting about how to "get past" the gitgitgadget bot checks.

Feel free to open a PR at https://github.com/gitgitgadget/gitgitgadget/ (yes, I assume that Typescript is not your forte, but the error message should be easy enough to `git grep` and to augment).
