### ISSUE TITLE
CI failure on the Git `win build` for `xterm-256color` 

### ISSUE THREAD

**Issue by PhilipOakley** [gitgitgadget/git#1284]
This is a cross link to the report [git-for-windows/git] CI failure on the Git `win build` for `xterm-256color` ([Issue #3940](https://github.com/git-for-windows/git/issues/3940)). The same error occurs when I set up the GGG [PR](https://github.com/gitgitgadget/git/pull/1282).

Is this a known issue?

**Comment by dscho** [comment]
Just like https://github.com/git-for-windows/git/issues/3940, this ticket is not about the `xterm-256color` warning at all, but about the `.tmp` folder not being deleted by the GitHub Action `setup-git-for-windows-sdk`.

And that issue has been addressed, so I will close this ticket?

In the future, could I ask you to tie up loose ends yourself when you reported the same issue in multiple places?
