### ISSUE TITLE
[FeatureRequest][git config]Add support for key names with underscores

### ISSUE THREAD

**Issue by sebma** [gitgitgadget/git#1318]
Hi,

Key names with underscores are not supported by `git config` : 
```conf
[user]
name = name
email = email@email.com
custom_field = AAA
```
```bash
$ git config --global user.custom_field 
error: invalid key: user.custom_field
```
Source : https://stackoverflow.com/q/11364044

Is it possible to add support for key names with underscores ?

**Comment by dscho** [comment]
Thank you for writing up a feature request. However, this is not the place the Git projects expects such requests (gitgitgadget/git is not even owned by the Git project): please send it to the Git mailing list. See https://git-scm.com/community for more details.

**Comment by sebma** [comment]
@dscho Hi, Quoting from https://git-scm.com/community : 

> Community
> Mailing List
> General questions or comments for the Git community can be sent to the mailing list by using the email address [git@vger.kernel.org](mailto:git@vger.kernel.org).
> 
> **_If you wish to report any possible bug for Git, please use this mailing list as well._**
> 
> **_You do not need to subscribe_**: you will be Cc'd in replies. Please keep the Cc list intact when replying (use "Reply to all"). Greylisting may delay your first post for a few hours. Note also that **_the list only accepts plain-text email_**; please disable HTML in your outgoing messages.

 So I have sent a Text-Only email with Thunderbird to git@vger.kernel.org but I got a failure notice from the mailer daemon saying : 

> Your address is not liked source for email

What does it mean ?

**Comment by dscho** [comment]
This sounds similar to https://lore.kernel.org/git/YuvyGzevAMWyd0K5@mit.edu/. I have no clue how to investigate such problems.

**Comment by sebma** [comment]
@dscho What's my next move ?

**Comment by dscho** [comment]
I don't know. Maybe there is a way to contact a list owner? I have no experience with this.

**Comment by phil-blain** [comment]
> Your address is not liked source for email

It can also mean that your email provider is flagged by the Git mailing list as being known for being used by accounts that send spam, probably. 

Your best bet is to write to the list using another email address :)
