### ISSUE TITLE
Drop support for obsolete MSys environments

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/git#1319]
According to https://lore.kernel.org/git/c9aec5b6-0a78-a580-3658-5189bd2075a6@kdbg.org, the last known Windows user of pre-MSYS2 build environments has switched to Git for Windows' environment.

Therefore, we can drop the msysGit/MSys parts of `config.mak.uname`.

**Comment by Harshil-Jani** [comment]
Hey ! @dscho I would like to work on this as a part of my " getting involved into the git " contribution . `[Newbie]`.

**Comment by dscho** [comment]
Go right ahead! Do you need any guidance in addition to what's written up in the ticket?

**Comment by Harshil-Jani** [comment]
@dscho  I need some help to think clearly about it. For now, All I can sense is that we need to clean up the support from [this line here](https://github.com/git/git/blob/a0789512c5a4ae7da935cd2e419f253cb3cb4ce7/config.mak.uname#L680) reffering to THIS_IS_MSYSGIT since it's no longer used.

**Comment by dscho** [comment]
@Harshil-Jani have you studied the surrounding code in detail and understood what it does? I'm afraid that it would take me longer to explain these `if`/`else` constructs than to write up the patch addressing this here ticket.

**Comment by Harshil-Jani** [comment]
@dscho If this is not on the priority list then please let me take some time ( Three days max )  to go through the config and understand how it works for different environments. My current understanding is that there are two implementations for git on Windows. 

1.  If kernel name is [Windows](https://github.com/git/git/blob/a0789512c5a4ae7da935cd2e419f253cb3cb4ce7/config.mak.uname#L413)
2.  If kernel name is [MinGW](https://github.com/git/git/blob/a0789512c5a4ae7da935cd2e419f253cb3cb4ce7/config.mak.uname#L625)

And there is currently the duplication of some variables like `NO_GETTEXT` .  So, We need to remove them and  also clean up around ..THIS_IS_MSYSGIT.

**Comment by dscho** [comment]
> 1. If kernel name is [Windows](https://github.com/git/git/blob/a0789512c5a4ae7da935cd2e419f253cb3cb4ce7/config.mak.uname#L413)

There [is not really a kernel name "Windows"](https://github.com/git/git/blob/a0789512c5a4ae7da935cd2e419f253cb3cb4ce7/config.mak.uname#L18).

But that's irrelevant for the sake of this ticket, anyway, that section is about using Visual C, which has nothing to do with the MSys support.

> 2\. If kernel name is [MinGW](https://github.com/git/git/blob/a0789512c5a4ae7da935cd2e419f253cb3cb4ce7/config.mak.uname#L625)

It's not the "kernel" name. The kernel is still Win32, even for `mingw-w64`. But the _system_ name (i.e. the output of `uname -s`) starts with `MINGW`.

Crucially, this "MINGW" condition holds true for three pretty different scenarios:

- The current Git for Windows SDK
- The obsolete Git for Windows v1.x SDK (also known as "msysGit")
- The obsolete MSys environment (retroactively also known as "MSys v1.x")

Technically, there is also a fourth environment, which is [MSYS2](https://msys2.org/). I just equate this with the Git for Windows SDK because the latter is a friendly fork of the former.

For this here ticket, the most relevant part of this is that 2./3. are handled in the `MINGW` clause, too, and support for them takes up space and maintenance and needs to go. The `MINGW` clause should only handle 1. going forward.

> And there is currently the duplication of some variables like `NO_GETTEXT` . So, We need to remove them and also clean up around ..THIS_IS_MSYSGIT.

I would strongly caution against blowing this ticket up more than it has to be.

The task is to understand enough to remove support for MSys and msysGit, and that's enough material for one contribution. Let's get this done before even thinking about further deduplication/cleanup work.

**Comment by rimrul** [comment]
Can this issue be merged, now that #1433 made it to master?

**Comment by dscho** [comment]
> Can this issue be merged, now that #1433 made it to master?

Yes!
