### ISSUE TITLE
gitk doesn't work on macOS Monterey

### ISSUE THREAD

**Issue by mikewy0527** [gitgitgadget/git#1388]
I install git with `brew install git` on my machine, and try to using `gitk`, but it startup failed with the following messages:
```
Error in startup script: 58:103: execution error: Not authorized to send Apple events to System Events. (-1743)
    while executing
"exec osascript -e [format {
        tell application "System Events"
            set frontmost of processes whose unix id is %d to true
        end te..."
    invoked from within
"if {[tk windowingsystem] eq "aqua"} {
    exec osascript -e [format {
        tell application "System Events"
            set frontmost of processes ..."
    (file "/usr/local/bin/gitk" line 12295)
```
Test environment:
```
macOS Monterey 12.6
git version 2.38.1
tcl-tk: stable 8.6.12
wish8.5
```
Then I google and found this mailing-list discussing the same issue: [Gitk doesn't work on macOS Mojave](https://www.mail-archive.com/git@vger.kernel.org/msg155599.html), and I test base on its patch [[PATCH] gitk: fix MacOS 10.14 "Mojave" crash on launch](https://www.mail-archive.com/git@vger.kernel.org/msg155998.html) (Signed-off-by: Eric Sunshine), it works. Here is my change code for test (no different with mentioned patch except the diff-header and whitespace):
```
diff --git a/gitk-git/gitk b/gitk-git/gitk
index 0ae7d68590..c8a4185156 100755
--- a/gitk-git/gitk
+++ b/gitk-git/gitk
@@ -12293,11 +12293,13 @@ if {[catch {package require Tk 8.4} err]} {

 # on OSX bring the current Wish process window to front
 if {[tk windowingsystem] eq "aqua"} {
-    exec osascript -e [format {
-        tell application "System Events"
-            set frontmost of processes whose unix id is %d to true
-        end tell
-    } [pid] ]
+    catch {
+        exec osascript -e [format {
+            tell application "System Events"
+                set frontmost of processes whose unix id is %d to true
+            end tell
+        } [pid] ]
+    }
 }

 # Unset GIT_TRACE var if set
```
Eric Sunshine's patch mentioned that `git-gui not automatically become the foreground application on "Mojave"`:
```
In contrast, git-gui does not crash since it deliberately[2] catches and
ignores Apple Events errors. This does mean that git-gui will not
automatically become the foreground application on "Mojave", which is a
minor inconvenience but far better than crashing outright as gitk does.
```
but I can't reproduce on my machine, maybe I was resolved. Anyway, both `git-gui` and `gitk applied patch` automatically become the foreground application.

I would like to know whether this issue will be fix, Thanks  ^_^

**Comment by dscho** [comment]
Thank you for writing up a bug report. However, this is not the place the Git projects expects bug reports: please send it to the Git mailing list. See https://git-scm.com/community for more details.
