### ISSUE TITLE
Make `check-whitespace`  failures more helpful

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/git#1395]
Every once in a while, the `check-whitespace` runs fail in a GitGitGadget PR and somebody has to explain how to fix them (see e.g. [the PR comment I just posted](https://github.com/gitgitgadget/git/pull/1394#issuecomment-1288176066)).

It would be good if we used [a workflow command](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions) to give more helpful output than:

![image](https://user-images.githubusercontent.com/127790/197410633-d61b4c21-a0d3-489f-8d2d-4981eab2d15c.png)

While at it, a newer version of `actions/checkout` could be used to avoid this warning:

![image](https://user-images.githubusercontent.com/127790/197410667-3772eb27-c053-469d-a861-60696fa6665a.png)

**Comment by dscho** [comment]
@webstech FYI

**Comment by webstech** [comment]
How about writing the errors and fix to the `job summary`?  It would take one click through away from the user (not having to look at the log).  Using `error|warning|notice` is problematic since they are single line in the annotations.

**Comment by dscho** [comment]
> How about writing the errors and fix to the `job summary`? It would take one click through away from the user (not having to look at the log). Using `error|warning|notice` is problematic since they are single line in the annotations.

Whatever works. We could also bring back the functionality that added a PR comment (i.e. reverting the revert at cc00362125c7726551d2b6bda85e1a4b17d0bc81), using the correct [`permissions`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) (I believe `issues: write` should do the trick).

As long as users get notified that they need to run `git rebase --whitespace=fix <base-commit>` 😁

**Comment by phil-blain** [comment]
This issue could be closed as PR #1444 has now reached `master` :)
