### ISSUE TITLE
Unexpected behavior of partial --help flag

### ISSUE THREAD

**Issue by lebedev** [gitgitgadget/git#1431]
Help flag behaves unexpectedly in some scenarios.

1. The command `git reset --h`
Expected behavior: error message about flag ambiguity (between `--help` and `--hard`).
Actual behavior: hard reset to HEAD.
2. The command `git reset --he`
Expected behavior: help about `reset` command`.
Actual behavior: error message about the unknown `he` flag.

**Comment by dscho** [comment]
@lebedev Thank you for writing up a bug report. However, this is not the place the Git projects expects bug reports: please send it to the Git mailing list. See https://git-scm.com/community for more details.

**Comment by lebedev** [comment]
Got it. Thanks
