### ISSUE TITLE
Document `AUTO_MERGE`

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/git#1471]
As the author of merge-ort mentioned a couple of times on the Git mailing list (e.g. [here](https://lore.kernel.org/git/CABPp-BGD3AZvXwmSHfQQ_xh_UqevH23kdBYijAWUk8GHu1q0Qw@mail.gmail.com/)), and of course [mentioned in a fantastic GitMerge talk](https://youtu.be/omGgXdXCt_8?t=280), there is a special pseudo-ref called `AUTO_MERGE`.

This pseudo-ref is very convenient e.g. after resolving merge conflicts, to validate the merge conflict resolutions by comparing to the state before any merge conflicts were resolved.

This pseudo-ref is not yet documented, though.

**Comment by phil-blain** [comment]
Hint: this pseudo-ref was added in 5291828df8.

**Comment by DataCrusade1999** [comment]
newbie here can I work on this if no one is working??

**Comment by dscho** [comment]
> newbie here can I work on this if no one is working??

@DataCrusade1999 sure! It is the custom in the Git project that tickets like this one are not assigned, but that volunteers simply state "I'm working on this" and then do that ;-)

**Comment by DataCrusade1999** [comment]
> @DataCrusade1999 sure! It is the custom in the Git project that tickets like this one are not assigned, but that volunteers simply state "I'm working on this" and then do that ;-)

Thanks for responding. I'm working on this issue.

**Comment by DataCrusade1999** [comment]
> > newbie here can I work on this if no one is working??
> 
> @DataCrusade1999 sure! It is the custom in the Git project that tickets like this one are not assigned, but that volunteers simply state "I'm working on this" and then do that ;-)

Thanks for responding. I'm working on this issue now.
