### ISSUE TITLE
More data should be dumped in case of protocol error

### ISSUE THREAD

**Issue by mvorisek** [gitgitgadget/git#1516]
`fatal: protocol error: bad line length character: Coul` error message took me quite a long time to understand.

The problem was: `Could not open input file: C:/...` output by a custom git filter. Initially, I was not sure where does the problem come from, and `GIT_TRACE=1` helped me but...

This is a feature request to improve the error message of git to include more data.

**Comment by mvorisek** [comment]
Actually the custom filter exists with non-zero code, so this should be primary reported instead of `bad line length character`.

**Comment by dscho** [comment]
Thank you for writing up a bug report. However, this is not the place the Git projects expects bug reports: please send it to the Git mailing list. See https://git-scm.com/community for more details.

**Comment by mvorisek** [comment]
I would say this is a feature request, where can I report it?

**Comment by dscho** [comment]
> where can I report it?

See https://git-scm.com/community
