### ISSUE TITLE
[BUG] "docs/.vuepress/.temp" Can`t be gnore

### ISSUE THREAD

**Issue by AkarinLiu** [gitgitgadget/git#1519]
I add "docs/.vuepress/.temp" at VuePress Project, but Is not valid.
![image](https://user-images.githubusercontent.com/58081491/233343306-5dd64e61-707b-48bf-994f-41c1cea37e55.png)

**Comment by dscho** [comment]
Thank you for writing up a bug report. However, this is not the place the Git projects expects bug reports: please send it to the Git mailing list. See https://git-scm.com/community for more details.
