### ISSUE TITLE
Is it possible to consider adding a `--confirm/-c` option to `git restore`

### ISSUE THREAD

**Issue by EdgarOrtegaRamirez** [gitgitgadget/git#1529]
It is easy to lose a work in progress by just missing `--staged` flag.

https://stackoverflow.com/questions/60554773/how-to-undo-a-git-restore-to-get-back-changes

**Comment by dscho** [comment]
Thank you for writing up a feature request. However, this is not the place the Git projects expects feature requests: please send it to the Git mailing list. See https://git-scm.com/community for more details.
