### ISSUE TITLE
push: Alias `--force-with-lease` as `--force-if-fetched`

### ISSUE THREAD

**Issue by veractor** [gitgitgadget/git#1574]
On first encounter, `--force-with-lease` seems a little cryptic, as it is not intuitive what "lease" is referred to in this context. I propose aliasing it as `--force-if-fetched` for "force only if the remote ref is fetched" for a more user-friendly phrasing because:
- It clearly signifies that the condition to forcing is as if `git fetch` just ran, where local refs are kept up-to-date with remote refs, i.e. the remote ref is as expected.
- Using the word "fetched" reuses existing git nomenclature, keeping it familiar.
- It matches the related ancillary option `--force-if-includes`.

**Comment by dscho** [comment]
@veractor please note that gitgitgadget/git is _not_ the Git project. This here issue tracker is used exclusively to gather ideas for no contributors, not to discuss Git's design.

If you want to propose changes to Git itself, you will need to follow the guidance in https://git-scm.com/community.
