### ISSUE TITLE
`diff` alias used to work in version 2.27, failing from version 2.28 onwards

### ISSUE THREAD

**Issue by aurianer** [gitgitgadget/git#1575]
Hi,

To output the diff of a specific commit, I created the alias `dici` (see below), `git dici 12345` or `git dici` to output the diff of the `HEAD`:
```
[alias]
    dici = !git diff ${1:-HEAD}^..${1:-HEAD}
```
a trace for this alias gives (same trace for both git 2.27 and 2.28!):
```
14:38:45.275964 git.c:439               trace: built-in: git diff a2028e7b^..a2028e7b a2028e7b  
```
The commit number is put again at the end of the command (the wanted alias is supposed to output only `git diff a2028e7b^..a2028e7b`), this was accepted by version 2.27 but not by the version 2.28. For now, my temporary fix is adding a bash comment at the end of the alias:
```
[alias]
    dici = "!git diff ${1:-HEAD}^..${1:-HEAD} #"
```
Note: the first alias still doesn't work with the latest git versions (tested with 2.40.0, 2.39.2, 2.37.5).

Is that expected behavior? if yes, how is the right/clean way to discard the command line argument of the alias?

Thanks in advance!

**Comment by dscho** [comment]
Thank you for writing up a bug report. However, this is not the place the Git projects expects bug reports: please send it to the Git mailing list. See https://git-scm.com/community for more details.
