### ISSUE TITLE
Replace usages of `test_i18ngrep` with `grep`

### ISSUE THREAD

**Issue by LemmingAvalanche** [gitgitgadget/git#1600]
> A #leftoverbit that is not relevant to the topic; we should clean
> these test_i18ngrep and replace them with a plain "grep".

#leftoverbit

From https://lore.kernel.org/git/xmqqbkcwuetq.fsf@gitster.g/T/#mcd856346e86c7d068ab18fc1a9e5a35e3527626a

**Comment by phil-blain** [comment]
This is pretty much done, the only remaining thing to do is actually removing `test_i18ngrep` from `test-lib-functions.sh`:

https://github.com/gitgitgadget/git/blob/25b0f41288718625b18495de23cc066394c09a92/Documentation/RelNotes/2.45.0.txt#L299-L303

**Comment by dscho** [comment]
> This is pretty much done

Excellent!
