### ISSUE TITLE
Git 2.44.0 Report 'MIDX does not contain the BTMP chunk '

### ISSUE THREAD

**Issue by fcharlie** [gitgitgadget/git#1673]
I am a maintainer of a code hosting platform. After I updated the server's Git to 2.44.0 today, the server reported "error: MIDX does not contain the BTMP chunk".

<img width="823" alt="image" src="https://github.com/gitgitgadget/git/assets/6904176/f1b28563-c310-4141-889c-694e9122596c">

Can this error be ignored to avoid misleading users?

Thanks

**Comment by dscho** [comment]
Thank you for writing up a bug report. However, this is not the place the Git projects expects bug reports: please send it to the Git mailing list. See https://git-scm.com/community for more details.
