### ISSUE TITLE
Allow `git config` to append a comment after a newly-added/-set/-replaced value

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/git#1680]
It is all nice and good to be able to call `git config this.that something` to configure something programmatically, but there is no way to leave a comment right now. It would be nice to say something like `git config --comment="I added this. -- banksy" this.that something` and end up with a config containing this:

```ini
[this]
  that = something # I added this. -- banksy
```

To accomplish this, one would need to:
- modify the [`write_pair()`](https://github.com/git/git/blob/v2.44.0/config.c#L3003-L3050) function, adding another function parameter (`const char *comment`?) that is then also [appended to `&sb`, if non-`NULL`](https://github.com/git/git/blob/v2.44.0/config.c#L3026)
- modify [the function signature of `git_config_set_multivar_in_file_gently()`](https://github.com/git/git/blob/v2.44.0/config.c#L3195-L3198) to accept the same parameter, adjusting all its callers to simply pass `NULL`
- pass this parameter in the two callers of `write_pair()` in the `git_config_set_multivar_in_file_gently()` function ([#1](https://github.com/git/git/blob/v2.44.0/config.c#L3248), [#2](https://github.com/git/git/blob/v2.44.0/config.c#L3402)
- append a new file-local variable to [`builtin/config.c`'s list of file-local variables](https://github.com/git/git/blob/master/builtin/config.c#L23-L46) and add a command-line option [to `git config`'s](https://github.com/git/git/blob/master/builtin/config.c#L137-L177), then ensuring that `cmd_config()` verifies that this option is only used in conjunction with `ACTION_SET_ALL`, `ACTION_ADD` or `ACTION_REPLACE_ALL`, otherwise error out with an error message
- modify [`cmd_config()`](https://github.com/git/git/blob/master/builtin/config.c#L672) to pass the `comment` to `git_config_set_multivar_in_file_gently()` when setting/adding/replacing ([#1](https://github.com/git/git/blob/master/builtin/config.c#L892-L894), [#2](https://github.com/git/git/blob/master/builtin/config.c#L900-L903), [#3](https://github.com/git/git/blob/master/builtin/config.c#L909-L911); there are two more callers, but they are _unsetters_)
- document the option in `Documentation/git-config.txt`
- add a test case to `t/t1300-config.sh`.

See also https://discord.com/channels/1042895022950994071/1213052410281467906/1213052410281467906

**Comment by rseichter** [comment]
Thank you for taking the time to write up this issue. I didn't expect my question in Discord and our subsequent brief discussion to lead us here, but surprises do happen. 😉

**Comment by rseichter** [comment]
@dscho I took my first baby steps in #1681. Your hints were very useful, and I only made modifications in a small number of additional places the compiler complained about. My manual tests worked, but before I invest more time in updating docs and the Git test suite, I'd like to hear your take on the changes I made so far. Cheers.

**Comment by LemmingAvalanche** [comment]
PR closed since this is in `master` 3256584c36f (Merge branch 'rs/config-comment', 2024-04-05)

I guess this can be closed?
