### ISSUE TITLE
Ignore specific changes but not the entire file

### ISSUE THREAD

**Issue by aboqasem** [gitgitgadget/git#1703]
The problem with:

```sh
git update-index [--skip-worktree|--assume-unchanged]
```

Is that it ignores the entire file. Is there a plan to support something that remembers what was exactly ignored, and if there are changes to it, either un-ignore the file, or display the hunks that were changed?

Something like committing the change but not actually committing it.

**Comment by dscho** [comment]
Thank you for writing up a feature request. However, this is not the place the Git projects expects feature requests: please send it to the Git mailing list. See https://git-scm.com/community for more details.
