### ISSUE TITLE
Requesting feedback on whether changes are needed in the submodule documentation.

### ISSUE THREAD

**Issue by Agent-Hellboy** [gitgitgadget/git#1753]
* main_repo
   * submodule
     * subsubmodule
     
If we add a new commit with changes in the submodule, and within that commit, we change the remote URLs of the subsubmodule, running git submodule sync --recursive will not sync those remote URLs until we update the submodule.

Should we document this behavior, or can it be managed using absorbgitdirs, or is it assumed that people will understand the need to run submodule sync multiple times in such scenarios?

**Comment by dscho** [comment]
This is not a Windows-specific issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
