### ISSUE TITLE
Typos?

### ISSUE THREAD

**Issue by TheGiraffe3** [gitgitgadget/git#1833]
I decided to check the documentation with a spellcheck. It threw out a few problems. I've eliminated most of them as not applicable, but there's an instance of "cant" and an instance of "wont". My question is, would adding a ' single quotation mark break the string they're in?
https://github.com/TheGiraffe3/git/actions/runs/12158845198/job/33907663392

My apologies if this is too small for an issue.

**Comment by dscho** [comment]
@TheGiraffe3 Thank you for writing up a bug report. However, this is not the place the Git projects expects bug reports: please send it to the Git mailing list. See https://git-scm.com/community for more details.
