### ISSUE TITLE
Allow `reset <tag>` in `git rebase -ir`

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/git#199]
The interactive rebase allows resetting `HEAD` to a specified revision, but it currently cannot handle tags. Let's fix that.

See https://public-inbox.org/git/nycvar.QRO.7.76.6.1903132322420.41@tvgsbejvaqbjf.bet/

**Comment by agrn** [comment]
I just tried to reset to a tag with `git rebase -ir` and it worked, what am I missing here?

**Comment by dscho** [comment]
> I just tried to reset to a tag with `git rebase -ir` and it worked, what am I missing here?

Did you issue something like `reset v2.23.0`? In my case, this failed, but I did not re-try recently, I have to admint.

**Comment by agrn** [comment]
Hmm, I tried to reset to a lightweight tag and it worked (on v2.23.0), but I just tried to reset to an annotated tag and it failed.  Now I understand.

**Comment by Morteza43** [comment]
https://github.com/gitgitgadget/git/issues/199#issue-445284150

**Comment by LemmingAvalanche** [comment]
This seems to work on git version 2.42.0? I'm not completely sure that I understand the issue.

This works with an annotated tag:

```
label onto

# Branch b
reset onto
pick 0c6e48d commit
pick c15c869 commit
pick b455456 commit
label branch-point
pick eb741d4 commit
pick c3cff52 commit
pick 47eb2a3 commit
pick 341a5a4 commit
label b

reset branch-point-tag # annotated tag
merge -C 017ad1b b # Merge branch 'b' into a
```
Deferencing (term?) to the commit with `^0` seems to work the same way:

```
...
reset branch-point-tag^0 
...
```

**Comment by dscho** [comment]
@LemmingAvalanche I bet it was 82766b29611aea7c3fb42a99debfba1436852d38 that fixed this. Could you verify?

**Comment by LemmingAvalanche** [comment]
@dscho Confirming that:

- This works (rebase succeeds) on `82766b2`
- This does _not_ work on the antecedent commit (`82766b2^1`)

Failed rebase:

```
hint: Could not execute the todo command
hint: 
hint:     reset tag-branch-point
hint: 
hint: It has been rescheduled; To edit the command before continuing, please
hint: edit the todo list first:
hint: 
hint:     git rebase --edit-todo
hint:     git rebase --continue
```

**Comment by dscho** [comment]
@LemmingAvalanche thank you for confirming!
