### ISSUE TITLE
range-diff: add support for `--left-only` and `--right-only`

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/git#206]
When contributing patches to Git, developers often need to compare in what form those patches made it upstream (e.g. to pick up fixes made by the Git maintainer in preparation for a new iteration). In such a case, a `--left-only` (or `--right-only`) option would come in real handy, to allow `git range-diff --left-only <branch>..upstream/pu` to skip commits that are upstream only (as there will be a metric ton of them).

**Comment by webstech** [comment]
Are there four possible outputs to be filtered (<>=!)?  Maybe a --range-filter= option to allow one or more of:
U - unmerged (left only)
C - changed (right only)
M - merged 
D - merged but not the same

These may not be the best terms but the help and the code do refer to the right side as the newer version.  --out-filter= may be more accurate but do not want to add an option that may get used for a new diff option.

**Comment by dscho** [comment]
Maybe at some stage this might be interesting, but my use case is pretty clear: I only want to suppress lines with unmatched commits from one side. FWIW I implemented this in https://github.com/gitgitgadget/git/pull/869.

**Comment by Denton-L** [comment]
Closed by 1e79f97326 (range-diff: offer --left-only/--right-only options, 2021-02-05).
