### ISSUE TITLE
Having grep support the -o option like GNU grep et al

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/git#232]
We have most of the code for this already in the form of our color hi-lighting, it would mostly just be a matter of "just print out the stuff you'd have colored", with the small exception that if you have more than one match on a line they should be printed out on their own lines.

Copied from: https://public-inbox.org/git/87in9ucsbb.fsf@evledraar.gmail.com/

**Comment by bbolli** [comment]
I think this was already implemented in 9d8db06eb4a5 ("grep.c: teach 'git grep --only-matching'", 2018-07-09).

**Comment by dscho** [comment]
@bbolli indeed! Thank you!
