### ISSUE TITLE
Fix flaky "t0021.15 required process filter should filter data"

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/git#241]
This test case seems to fail infrequently, most often in the `linux-gcc` job. See e.g. https://dev.azure.com/gitgitgadget/git/_build/results?buildId=9226&view=ms.vss-test-web.build-test-results-tab&runId=19716&resultId=100893&paneView=debug

**Comment by tgummerer** [comment]
https://public-inbox.org/git/20190820065625.128130-1-t.gummerer@gmail.com/

I think we're good to close this

**Comment by dscho** [comment]
Good call! It already made it to `next`: https://github.com/git/git/commit/58166c2e9d9a3bbf6eee9e3e8710d92985e6edab, so I expect it to make it to `master` relatively soon (which is when GitGitGadget usually closes PullRequests, so I kinda thought about the same for issues, although that's a more manual process).
