### ISSUE TITLE
Don't run Cocci on compat/ files that are pulled externally

### ISSUE THREAD

**Issue by Denton-L** [gitgitgadget/git#248]
Since some files in compat/ are pulled externally, ideally we should not update them unless absolutely necessary. As a result, we should find what these files are and blacklist Cocci from being run on them.

One thing to consider, some files are Windows-only and are never Coccinelled whenever we compile on Windows. Do we want to make Cocci run on _all_ files, regardless of whether or not they're compilable on the current platform? Upside is that [Szeder found some files that could be patched that we weren't catching](https://public-inbox.org/git/20190502000422.GF14763@szeder.dev/#t). Downside is that there is no way to test the code to ensure that it works properly.

Another stretch goal is to do the `extern` removal on files that we _do_ own in compat/, since those were explicitly excluded during the big `extern` cleanup since those were intentionally excluded in b199d7147a (*.[ch]: remove extern from function declarations using sed, 2019-04-29) and 554544276a (*.[ch]: remove extern from function declarations using spatch, 2019-04-29).

**Comment by Denton-L** [comment]
Currently being cooked here: https://github.com/gitster/git/commits/dl/cocci-everywhere

**Comment by dscho** [comment]
Done cooking. It's in `master`.
