### ISSUE TITLE
Fix flaky t5516-fetch-push (test case 79 - deny fetch unreachable SHA1, allowtipsha1inwant=true)

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/git#257]
This seems to fail every once in a while, especially in Git for Windows' experimental MSVC job of our Azure Pipeline.

The issue seems to be that multiple processes report fatal errors at the same time, and our grep fails to verify that the expected error message was printed because they were interleaved. Example:

```
++ grep 'remote error:.*not our ref.*64ea4c133d59fa98e86a771eda009872d6ab2886$' err
++ echo 'error: '\''grep remote error:.*not our ref.*64ea4c133d59fa98e86a771eda009872d6ab2886$' 'err'\'' didn'\''t find a match in:'
error: 'grep remote error:.*not our ref.*64ea4c133d59fa98e86a771eda009872d6ab2886$ err' didn't find a match in:
++ test -s err
++ cat err
fatal: git uploadfatal: remote error: upload-pack: not our ref 6-pack: not our ref 64ea4c1334ea4c133d59fa98e86a771eda009872d6ab2886
d59fa98e86a771eda009872d6ab2886
```

**Comment by dscho** [comment]
Whoops, I already had opened https://github.com/gitgitgadget/git/issues/240 for this... Closing here.

**Comment by 0534455145** [comment]
https://ali123451.substack.com/subscribe?params=%5Bobject%20Object%5D
