### ISSUE TITLE
escape branch name with leading # in example of no upstream set

### ISSUE THREAD

**Issue by robstoll** [gitgitgadget/git#311]
say you have a branch named `#42-my-lovely-branch` and would like to push it but forgot to set the upstream branch. You get the following error message:
```
fatal: The current branch #42-my-lovely-branch has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin #42-my-lovely-branch
```
This cannot be copy & paste as `#42-my-lovely-branch` should be escaped with a backslash as follows:
```
    git push --set-upstream origin \#42-my-lovely-branch
```

As webtech mentioned here: https://github.com/gitgitgadget/gitgitgadget/issues/112
 > Using # in the branch name is valid but will cause unexpected problems. If you are using windows cmd shell, # does not need to be escaped. On other shells, it needs to be escaped or quoted. Not sure git should need to figure out where it is running and determine if it needs to escape any characters in the branch name. If the # had not been the first character in the branch name the cut and paste may have worked with unexpected results.

**Comment by dscho** [comment]
Please note that most Git developers do not pay attention to this bug tracker, but _only_ to bug reports via [the Git mailing list](mailto:git@vger.kernel.org).

**Comment by webstech** [comment]
Sorry for not redirecting you to the mailing list.

**Comment by dscho** [comment]
@robstoll did you send your bug report?

**Comment by robstoll** [comment]
@dscho nope, I guess it's not important enough for me. So close the issue if you like

**Comment by dscho** [comment]
> So close the issue if you like

I will close it for you. Next time, feel free to do that yourself, though.
