### ISSUE TITLE
Add config option corresponding to `--rebase-merges` flag

### ISSUE THREAD

**Issue by dakotahawkins** [gitgitgadget/git#318]
In my workflow, while it's uncommon to encounter merge commits during a rebase operation, when they are encountered I pretty much always want this behavior. Since it's rare, I pretty much always forget to ask for it, with interesting and confusing consequences.

Is there any appetite for a `rebase.rebaseMerges` boolean that could drive the default for this option?

Thanks,

Dakota

**Comment by dscho** [comment]
Good idea!!!

**Comment by LemmingAvalanche** [comment]
`rebase.rebaseMerges` exists now. Close?

**Comment by dscho** [comment]
Indeed, and [here is the documentation](https://git-scm.com/docs/git-config#Documentation/git-config.txt-rebaserebaseMerges). Thank you!
