### ISSUE TITLE
[META] gitgitgadget/git is missing tags from git/git

### ISSUE THREAD

**Issue by dakotahawkins** [gitgitgadget/git#319]
The latest version tag is `v2.18.0`, @dscho can you update whatever process you use to sync this fork?

Edit: Noticed this doing an initial `make configure` on _my_ fork of this.

**Comment by dscho** [comment]
Let's script this. Would you have time to come up with that script? It would compare the tags of two remotes, obtained via `ls-remote`, in my mind, and construct a `push` command-line from that diff. I would then copy this script into the automation that already mirrors the branches.

**Comment by dscho** [comment]
> I thought I would find the existing mirroring in [gitgitgadget/gitgitgadget](https://github.com/gitgitgadget/gitgitgadget), but nothing there seemed to be doing it.

It is a non-YAML build: https://dev.azure.com/gitgitgadget/git/_build?definitionId=8

> The script in [dakotahawkins/sync-tags](https://github.com/dakotahawkins/sync-tags) should do exactly what you want.

I took the liberty of coming up with a simpler solution:

```sh
die () {
    echo "$*" >&2
    exit 1
}

for d in git gitgitgadget
do
    git ls-remote --tags https://github.com/$d/git | grep -v '\^{}$' | sort >tags.$d ||
    die "Could not enumerate tags in $d"
done

refspec="$(comm -23 tags.git tags.gitgitgadget | tr '\t' :)" ||
die "Could figure out missing tags"
```

... and then pushing `$refspec` unless it is empty. See this run that synchronized the initial slur of tags: https://dev.azure.com/gitgitgadget/git/_build/results?buildId=15228

**Comment by dscho** [comment]
(Of course, I realize that this will not synchronize tags unless a _branch_ triggers the build, as tag updates can only trigger YAML builds, but that's better than not synchronizing the tags at all.)

**Comment by dscho** [comment]
>  I would probably just destructively fetch branches and tags from the upstream at the same time and push those.

About tags: agree, branches, we already force-push. Pruning is a different matter: this would potentially fail (or close PRs), so I would like to avoid that.
