### ISSUE TITLE
Emphasise the cherry-pick --skip option

### ISSUE THREAD

**Issue by Denton-L** [gitgitgadget/git#320]
In the case of conflicts while cherry-picking, one can pass in the `--skip` flag and it'll skip the problematic patch. However, this option is not suggested by completions nor is it suggested when running `git status`, unlike when we're rebasing.

**Comment by Denton-L** [comment]
Currently cooking here: https://github.com/gitster/git/commits/dl/complete-cherry-pick-revert-skip

**Comment by Denton-L** [comment]
Merged here: https://github.com/gitster/git/commit/21db12c9ea572a34bd9d4388135b1a9553c28133

**Comment by dscho** [comment]
> Merged here: [gitster@21db12c](https://github.com/gitster/git/commit/21db12c9ea572a34bd9d4388135b1a9553c28133)

Great!

FWIW you can close these gitgitgadget/git issues by adding a line `This fixes <URL>` into the commit message. Worked for me in the past ;-)
