### ISSUE TITLE
[META] Are GitHub issues in this repo considered "official"?

### ISSUE THREAD

**Issue by borekb** [gitgitgadget/git#333]
Though I'm now relatively old and have been around when mailing lists were the primary tool for most OSS projects, I never really liked them or understood how to use them efficiently. So it was exciting to me when I encountered this GitHub repo!

I've noticed it's used not only for pull requests (as noted on https://gitgitgadget.github.io/) but there are also some issues being created here, and they look like "normal" feature requests / bug reports for the Git project. Are those somehow forwarded to mailing lists with the main discussion happening there, or is GitHub an additional, semi-official place now?

Anyway, the repo looks fantastic, with things like Weekly Digests etc. Thanks for the effort that went into it!

**Comment by dscho** [comment]
No, they are not official.

But this answer is not official, either.

You need to ask on the Git mailing list.
