### ISSUE TITLE
Add a "summary" pretty format

### ISSUE THREAD

**Issue by Denton-L** [gitgitgadget/git#340]
According to Documentation/SubmittingPatches,

```
[[commit-reference]]
If you want to reference a previous commit in the history of a stable
branch, use the format "abbreviated sha1 (subject, date)",
with the subject enclosed in a pair of double-quotes, like this:

....
	Commit f86a374 ("pack-bitmap.c: fix a memleak", 2015-03-30)
	noticed that ...
....

The "Copy commit summary" command of gitk can be used to obtain this
format, or this invocation of `git show`:

....
	git show -s --date=short --pretty='format:%h ("%s", %ad)' <commit>
....
```

But why must we manually enter this format? It seems commonplace enough that we should be able to specify something like `git show -s --pretty=summary` and it'll do the same thing.

One thing to consider: can we override the configured date settings? If a user _doesn't_ provide a --date option, can we automatically assume --date=short?

**Comment by Denton-L** [comment]
A draft exists here: https://github.com/Denton-L/git/tree/ready/pretty-summary

Waiting on the v2.24.0 to release then I'll submit it.

**Comment by Denton-L** [comment]
Submitted here: https://public-inbox.org/git/cover.1572897736.git.liu.denton@gmail.com/T/#t

**Comment by phil-blain** [comment]
@Denton-L this one can be closed right ? It has been implemented as `--reference`.

**Comment by Denton-L** [comment]
Yep, I forgot to close this issue before. Thanks for pointing it out.
