### ISSUE TITLE
Add support for Co-authored-by: in commit

### ISSUE THREAD

**Issue by Denton-L** [gitgitgadget/git#343]
Since [GitHub supports the Co-authored-by: trailer](https://github.blog/2018-01-29-commit-together-with-co-authors/), I'd say it's a defacto standard.

Perhaps we could add an option such as `git commit --coauthor="John Smith <js@something.com>"  --coauthor="Smith John <sj@something.com>"` which would automatically add the trailers. This should happen right before the SOB lines.

Things to consider:

* what other commands should get this option (anything supporting --signoff?)

* Do we want a config option for this? (Currently --signoff doesn't have one, does this deserve one?)

**Comment by To1ne** [comment]
I've sent a patch for this https://public-inbox.org/git/20191008074935.10972-1-toon@iotcl.com/T/#u

**Comment by Denton-L** [comment]
Individual trailer options will never be supported: https://lore.kernel.org/git/xmqqft8b6h52.fsf@gitster.c.googlers.com/

**Comment by phil-blain** [comment]
A more general option `--trailer` was added in [that thread on the Git mailing list](https://lore.kernel.org/git/pull.901.git.1615446968597.gitgitgadget@gmail.com/t/#u), which came out in Git 2.32.0: https://github.com/gitgitgadget/git/blob/4b6846d9dcd391164b72bd70e8a0c0e09776afe3/Documentation/RelNotes/2.32.0.txt#L55-L57

With this option you can do:

```bash
git commit --trailer "Co-authored-by: Jane Doe <their.email@domain.com>"
```

You can also setup a [config variable](https://git-scm.com/docs/git-interpret-trailers#Documentation/git-interpret-trailers.txt-trailerlttokengtkey) to make it easier:
```bash
git config --global trailer.co.key "Co-authored-by"
git commit --trailer=co:"Jane Doe <their.email@domain.com>"
```

If your co-author has already authored some commits in the project's history, or you have another automated way to get their full name and email (LDAP for example), you can [make that even shorter](https://git-scm.com/docs/git-interpret-trailers#Documentation/git-interpret-trailers.txt-trailerlttokengtcmd):
```bash
git config --global trailer.co.key "Co-authored-by"
git config --global alias.who = '!f () { git --no-pager -c mailmap.blob=origin/master:.mailmap log -1 --format="%aN <%aE>" --author="$1" -i origin/master;  }; f'
git config --global trailer.co.cmd "git who"
git commit --trailer=co:jane
```
