### ISSUE TITLE
merge: add a --autostash option

### ISSUE THREAD

**Issue by agrn** [gitgitgadget/git#394]
`git-rebase` has a `--autostash` option to save unstaged changes before performing a rebase, and to restore them afterwards.  Perhaps it could be interesting to add the same option to `git-merge`.  Perhaps `git-stash` could be libified before we get down to this?

This was brought up in a discussion with a coworker of mine, where we talked about `rebase --autostash`, and I naïvely said “well, merge should have it too.”  I was kind of surprised to see I was wrong on that.

**Comment by Denton-L** [comment]
RFC here: https://public-inbox.org/git/cover.1571246693.git.liu.denton@gmail.com/T/#t

**Comment by Denton-L** [comment]
Merged in bf10200871d9e7e1fc9f54aca9b2fe40bc4e4ac7.
