### ISSUE TITLE
Get rid of the `PRIuMAX` guard in `git-compat-util.h`

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/git#399]
As mentioned in https://public-inbox.org/git/xmqqsgzr2nkk.fsf@gitster-ct.c.googlers.com/t/#u:

The `%lld` format is supported on Linux and macOS, but not on Windows. Therefore, we use `PRIdMAX` instead and a cast the parameter to `intmax_t`.

The fact that `PRIdMAX` is used without any fallback definition in `git-compat-util.h` is a pretty good sign that we can drop the fallback for `PRIuMAX`, too.

**Comment by harry-hov** [comment]
Looking forward to this 😀

**Comment by dscho** [comment]
@harry-hov this is a really easy one. How about giving it a try?

**Comment by Denton-L** [comment]
Closed by e547e5a89e (Merge branch 'hv/assume-priumax-is-available-anywhere', 2019-12-05).

**Comment by dscho** [comment]
> (Unfortunately, I don't have permission to close issues here.)

@Denton-L once you accept the invitation I just sent, you should have the permission. I'll leave this issue open so you can try?

**Comment by Denton-L** [comment]
Thanks, it works!
