### ISSUE TITLE
Add a build option to skip linking all those built-ins to their dashed form

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/git#406]
Once upon a time, in a galaxy far, far away, a Git version still was developed under the impression that it should consist of little Unix tools that are cobbled together by Unix shell scripts. In those olden days, all of those tools lived in the `PATH`, using names that all started with `git-` and it was a great hodge podge that Unix graybeards were prone to love: almost a hundred executables cluttering the tab completion (at which Unix graybeards sneer regularly), spawned processes galore.

Fast forward into a more modern time, Git has almost no Unix script parts left, and many, many built-in commands. Those are commands that are contained in the `git` executable, can be called as `git <command>` instead of the "dashed" form `git-command`, and avoid at least one extra spawned process that way.

For ~~hysterical~~ historical reasons, even if there is pretty much no need whatsoever anymore to have, say, `git-add` in the `libexec/git-core/` directory, we do still hardlink all of those built-ins to the corresponding "dashed form", _just so_ that any old script that still expects, say, `git-read-tree` to be in its `PATH` (when calling scripts whose name are of the form `git-<script-name>` via `git <script-name>`, the `git` executable will take pains to prepend the `libexec/git-core/` directory to the `PATH`), when in reality it should call `git read-tree` instead, i.e. the "undashed" form.

It does take quite a while to link all those built-ins during a build, especially on Windows, where the `make` process uses a POSIX emulation layer (i.e. the MSYS2 runtime, a slightly modified Cygwin runtime), which takes _quite_ some time.

The Git maintainer indicated that they would be fine with a build-time option to _not_ link those built-ins. Eventually, this option should probably become the default.

**Comment by periperidip** [comment]
Hey dscho,
I am not able to wrap my head around this. The problem is that the "dashed" forms are called in as well for command like `git add` right( _i.e._ commands whose dashed forms exist?). And our goal is to prevent that from happening by adding a build option which skips those "dashed" built-ins as far as my understanding goes?

**Comment by dscho** [comment]
> The problem is that the "dashed" forms are called in as well for command like `git add` right( _i.e._ commands whose dashed forms exist?).

To be more precise: in addition to calling `git add`, you can also call `git-add` when scripting a new `git-<command>`. The latter form is deprecated for quite a while now, nevertheless we still hard-link `git` to `git-add` in `<prefix>/libexec/git-core/`.

That is, if your Git executable lives in `/usr/bin/git`, then it is also hard-linked to `/usr/libexec/git-core/git-add` (and likewise a _ton_ of other built-in commands).

BTW "built-in" means that the command is implemented directly inside the `git` executable, not just that it is implemented in C. For example, `git-remote-https` is implemented in C, but definitely is a separate executable that is spawned from `git`, by design.

Now, build Git's source code via `make` you probably saw this insanely long list of `BUILTIN <command>` at the end, right? That's the hard-linking stage.

Since those "dashed" forms are both unnecessary as well as deprecated, it would be a pretty okay thing to optionally skip that hard-linking stage altogether.

Having said all this, have you noticed that I already opened a "Work-in-Progress" Pull Request, as [noted above](https://github.com/gitgitgadget/git/issues/406#ref-pullrequest-509613730)?

**Comment by periperidip** [comment]
I appreciate your reply, I have understood it for the most part.
I noticed the "Work-in-Progress" PR just now. I wanted to ask you what work is still left to do in this issue? And direction should I proceed in now? 
I noticed that you were trying to add some lists and maybe an option called `ALL_PROGRAMS_AND_BUILT_INS`. Is that the direction we go in?

**Comment by dscho** [comment]
> what work is still left to do in this issue?

See https://github.com/gitgitgadget/git/pull/411#issuecomment-579794773

> you were trying to add some lists and maybe an option called `ALL_PROGRAMS_AND_BUILT_INS`.

It's not really a list, it is a variable that concatenates two lists... But yes, I think that this is the correct direction to go. Unless you find a better way, that is.

**Comment by phil-blain** [comment]
See also: https://github.com/gitgitgadget/git/pull/840

@dscho I guess we can close this here issue, right?

**Comment by dscho** [comment]
> See also: https://github.com/gitgitgadget/git/pull/840
> 
> @dscho I guess we can close this here issue, right?

I suppose :-)
