### ISSUE TITLE
builtin/commit: replace `sequencer_in_use`/`rebase_in_progress` combo by an `enum`

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/git#426]
In 116a408b6ffcb2496ebf10dfce1364a42e8f0b32, I introduced the variable `rebase_in_progress` to be able to discern between the situation where a `git cherry-pick` operation resulted in an empty patch vs a `git rebase` operation.

Junio pointed out in `https://public-inbox.org/git/xmqqr234i2q0.fsf@gitster-ct.c.googlers.com/` that these variables should probably be combined into a single `enum` that has three states:

- regular commit
- interrupted rebase
- interrupted cherry-pick

While at it, we should probably see whether we need to take care of `git revert`, too: it also could result in an empty patch.

**Comment by Fmstrat** [comment]
I'd like to take this on.

**Comment by Fmstrat** [comment]
@dscho So I wrote a patch that does this, however the DCO is proving problematic. GitHub is giving me the message saying there is no signoff, but I think it is because my GitHub username is not my full name (Full name is mentioned as the requirement in the SubmittingPatches doc).

Should I allow it to use Fmstrat instead of my full name?

https://github.com/gitgitgadget/git/pull/531

**Comment by dscho** [comment]
> however the DCO is proving problematic. GitHub is giving me the message saying there is no signoff, but I think it is because my GitHub username is not my full name (Full name is mentioned as the requirement in the SubmittingPatches doc).

Can you make sure that your `user.name` and `user.email` are set correctly, and then call `git commit --amend --reset-author`, then force-push? That should pacify the DCO bot.

**Comment by Fmstrat** [comment]
So now that the PR is approved, out of curiosity (having never contributed to `git`) what is the standard timeline for GitGitGadget's push to the mailing list and follow through?

And is this the best place to continue to look for issues I can contribute through? (I wasn't sure if the issue tracker here was the master list)

**Comment by dscho** [comment]
> So now that the PR is approved

That means nothing ;-)

> what is the standard timeline for GitGitGadget's push to the mailing list and follow through?

Well, at first you will have to `/submit` it (as described in [GitGitGadget's welcome message](https://github.com/gitgitgadget/git/pull/531#issuecomment-575328781))... before that, your contribution was not seen by the Git mailing list (my review on GitHub does not count, the Git project is not run on GitHub, this repository is a mere mirror of the official repository at git://git.kernel.org/pub/scm/git/git.git/).

**Comment by Fmstrat** [comment]
@dscho Yea, I'm blind, sorry about that. Thanks for all your help as I get up to speed here.

So I'm getting new errors related to the commit author now. The bot is reporting
```
Error: Could not determine full name of Fmstrat
```
I see it is pulled from the commit name here: https://github.com/gitgitgadget/gitgitgadget/blob/b452884464a2bf09069cb494d5fcd5276f7db3ea/lib/github-glue.ts#L353

But I'm not entirely sure where that is coming from. The `fuller` format for my commit shows:
```
Author:     Ben Curtis <nospam@nowsci.com>
AuthorDate: Thu Jan 16 17:55:49 2020 -0500
Commit:     Ben Curtis <nospam@nowsci.com>
CommitDate: Thu Jan 16 18:03:22 2020 -0500
```

**Comment by phillipwood** [comment]
This is already addressed in pu by pw/advise-rebase-skip

**Comment by phil-blain** [comment]
@dscho I think this issue can be closed :)
