### ISSUE TITLE
revert in rebase -i [RFC]

### ISSUE THREAD

**Issue by patrick-mcdougle** [gitgitgadget/git#431]
This is a request for comments [RFC] of a feature which would extend interactive rebase's todo list to add a new `revert` command.

### The Problem
Let's say you are working on a feature branch based off of master called `my-feature`. You work on your feature and you think it's all ready to be merged into master...

```
master:...--O
             \
my-feature:   O
```

Then you merge to master only to revert (using Ø to denote a revert) because you screwed something up (perhaps using the github UI). Now master looks like this:
```
master: ...--O----O-----O
              \  / \   /
my-feature:    O    \ /
revert-my-feature:   Ø
```

At this point most devs will go back to working on their feature by checking out the my-feature branch and working on a fix for their feature...
```
old-master:...--O
                 \
my-feature:       O---O
```

At this point there's a problem when you open a PR to master since the commit that you want to merge into master is already on master...so you need to rebase and revert the revert. HOWEVER, you can't splice the revert revert between your bugfix and the new tip of master using rebase and just applying the bugfix's diff to the tip of master causes conflicts. Usually at this point you just burn your branch down, create a new branch off of new master, revert your revert then cherry-pick your bugfix commit to the end and open a PR to master from the new branch.

### The Proposal
What if we added an option to interactive rebase to create a new revert commit onto the todo list?

In the example above, a dev would be able to get the sha of the revert from the `revert-my-feature` branch and do the following:

`git rebase -i master` (assuming origin had been pulled)

```
revert {the commit hash of Ø}
pick {the commit hash of the second bugfix commit}
```

While running the rebase, git would play this line in the todo list and create a revert of that commit at that point in the todo list. (as if you had ran `git revert {the commit hash of Ø}` at that point in the todo list.

Thoughts? Is this useful? Would such a feature be merged? I haven't written c in over 7 years, but I'm willing to give it a shot.

**Comment by Denton-L** [comment]
Hmm, this can already be done putting `break` and then manually running `git revert`. Would that suffice or does adding the `revert` command add anything in addition to that? You could ask the mailing list but I think that it wouldn't receive much love since it doesn't seem to add any additional value.

**Comment by dscho** [comment]
You could also insert a line `exec git revert <hash>`.

I fear, however, that the _underlying_ issue is that the rebase starts by generating a list of commits based on the commit graph, and the original commit simply is part of the commit history reachable from `master`.

The most common way to continue in this situation is to re-create the branch by rebasing (which skips the original commit) and then cherry-picking the original commit.

**Comment by patrick-mcdougle** [comment]
It seems like break certainly covers this case...now to figure out how to upgrade git on my mac...
