### ISSUE TITLE
Consolidate test_cmp_graph logic

### ISSUE THREAD

**Issue by Denton-L** [gitgitgadget/git#471]
This logic is duplicated many times in 

* t3430-rebase-merges.sh
* t4202-log.sh
* t4214-log-graph-octopus.sh
* t4215-log-skewed-merges.sh

Perhaps we could throw it all into a new `lib-log-graph.sh`?

**Comment by dscho** [comment]
Sounds like a good plan to me, and like a good first issue.

**Comment by abhishekkumar2718** [comment]
Hey @dscho 

I have been working on this issue and some test cases in t4202-log.sh provide their custom sanitize functions (example: `log --graph with full output`).

Is it worth it to convert all such cases or just the common cases?

**Comment by dscho** [comment]
> Is it worth it to convert all such cases or just the common cases?

If it does not add too much chatter, I guess converting all of them sounds like the better option to me. (If you need my opinion, that is.)

**Comment by Denton-L** [comment]
Fixed in 46703057c1a0f85e24c0144b38c226c6a9ccb737, thanks!
