### ISSUE TITLE
Accept contributions direct from gitforwindows/git/master forks?

### ISSUE THREAD

**Issue by PhilipOakley** [gitgitgadget/git#643]
Having created a potential improvement on top of Git for Windows master, it would be great if the contribution could be accepted directly, rather than appearing to be 'too big'.

This may conflate the issue of GitHub PR merge with the gitgitgadget patch submission process, but I felt it worth mentioning so as to avoid putting too many disincentives onto the Windows contributors.

e.g. https://github.com/PhilipOakley/git/tree/blameboundary

**Comment by dscho** [comment]
> Having created a potential improvement on top of Git for Windows master, it would be great if the contribution could be accepted directly, rather than appearing to be 'too big'.

By "accepted directly", you mean "directly into git.git's `master`"?

If so, I am afraid that that's impossible, already for one purely technical reason: git-for-windows/git's `master` is sufficiently different from git/git's that the patches might not even apply, and even if they do, the build and/or the test suite might fail.

So there really needs to be a separate contribution.

As to "too big", I am afraid I do not follow. Do you expect https://github.com/PhilipOakley/git/compare/blameboundary~4...blameboundary to be _too big_?

Apart from that, I fear that there is another misconception: namely, that a review in git-for-windows/git is enough to get a patch accepted into git/git. This is distinctly not so.

What _is_ true, however, is that I frequently accept git-for-windows/git PRs. And by "to accept" I not only mean that I merge them, but that I also accept the responsibility of upstreaming them, at an opportune time.

> This may conflate the issue of GitHub PR merge with the gitgitgadget patch submission process, but I felt it worth mentioning so as to avoid putting too many disincentives onto the Windows contributors.

First of all, please note that the "H" in "GitHub" really needs to be upper-case, there is no /θ/ sound in that name. I fixed the spelling for you this time.

Further, how would it avoid putting a disincentive onto Windows-based contributors if they had to handle the Git mailing list review _in addition_ to a Git for Windows PR? In contrast, I think that would very much disincentivize code contributions. I'd rather have the current contribution process where contributors who can stomach a mailing list-based review process go and open a GitGitGadget PR directly, and all others just go via the Git for Windows PR route.

**Comment by PhilipOakley** [comment]
>     Having created a potential improvement on top of Git for Windows
>     master, it would be great if the contribution could be accepted
>     directly, rather than appearing to be 'too big'.
>
> By "accepted directly", you mean "directly into git.git's master"?
>

That's would be the final destination for the submitted **patch** series
(via `pu`, `next`, to `master`)
>
> If so, I am afraid that that's impossible, already for one purely
> technical reason: git-for-windows/git's master is sufficiently
> different from git/git's that the patches might not even apply, and
> even if they do, the build and/or the test suite might fail.
>

That's exactly the point.
>
> So there really needs to be a separate contribution.
>
> As to "too big", I am afraid I do not follow. Do you expect
> PhilipOakley/git@blameboundary~4...blameboundary
> <https://github.com/PhilipOakley/git/compare/blameboundary~4...blameboundary>
> to be too big?
>
'We' (if the gadget is to help) need to separate the 4 patch series I
prepared, from the Git-for-Windows patches.

Maybe there could be a branch on gitgitgadget that is the
gitforwindows/master, so that relevant patch series could be provided
from there, should the submitted PR be 'on' that branch (or at least the
last Git-for-windows release tag, and not have an conflict with the
windows patches)

That ('too big') is the unfortunate GitHub response to a PR onto
git/master...

It says "X Can’t automatically merge. Don’t worry, you can still create
the pull request. ", and then "This comparison is big! We’re only
showing the most recent 250 commits "

> Apart from that, I fear that there is another misconception: namely,
> that a review in git-for-windows/git is enough to get a patch accepted
> into git/git. This is distinctly not so.
>
This is a request/suggestion regarding gitgitgadget which is to "Open
Pull Requests here to submit them to the Git mailing list"...

The enquiry was about that very aspect.

> What is true, however, is that I frequently accept git-for-windows/git
> PRs. And by "to accept" I not only mean that I merge them, but that I
> also accept the responsibility of upstreaming them, at an opportune time.
>
>     This may conflate the issue of GitHub PR merge with the
>     gitgitgadget patch submission process, but I felt it worth
>     mentioning so as to avoid putting too many disincentives onto the
>     Windows contributors.
>
> First of all, please note that the "H" in "GitHub" really needs to be
> upper-case, there is no /θ/ sound in that name. I fixed the spelling
> for you this time.
>
Sorry for my English.

> Further, how would it avoid putting a disincentive onto Windows-based
> contributors if they had to handle the Git mailing list review in
> addition to a Git for Windows PR?
>

Wrong addition. There is no review on the git-for-windows repo. The PR
is direct from the contributors fork to this here repo. This request is
a reduction in contributor effort.
>
> In contrast, I think that would very much disincentivize code
> contributions.
>

> I'd rather have the current contribution process where contributors
> who can stomach a mailing list-based review process go and open a
> GitGitGadget PR directly,
>
That is my request !!!

> and all others just go via the Git for Windows PR route.
>
>
Philip

**Comment by dscho** [comment]
> Maybe there could be a branch on gitgitgadget that is the gitforwindows/master, so that relevant patch series could be provided from there

Then any PR that targets that branch might not even apply cleanly to _any_ of the git/git (or gitster/git) branches! That would be totally not helpful.

> That ('too big') is the unfortunate GitHub response to a PR onto git/master...

That's because by targeting git-for-windows/git's `master`, you have all of Git for Windows' commit history. You need to rebase _your_ commits on top of the appropriate branch in git/git (or gitster/git) first, otherwise your PR won't be any good to the Git project.

> This request is a reduction in contributor effort.

I am afraid that the burden cannot be automated away. The rebase _has_ to happen, and it _can_ result in conflicts.

If you want to shy away from that rebase, you have two options:

- open a Git for Windows PR instead, and ask me to handle it.
- rebase your branch on top of git/git's `master` and work on that. It should compile on Windows just the same.

I understand the desire to have a tool to do all the tedious things for you. Some of those tasks _can_ be automated (although I remember you trying to prevent me from doing that in the past, under some guise that it would potentially make the process more opaque to the occasional lurker), but the rebase you're asking about is _not_ possible to automate, as too many things might require human interaction.

**Comment by dscho** [comment]
> I am afraid that the burden cannot be automated away

Therefore, I'll close this. And this ticket is not even a year old... 🎉
