### ISSUE TITLE
object: remove commit_count from parsed_object_pool

### ISSUE THREAD

**Issue by abhishekkumar2718** [gitgitgadget/git#657]
With 14ba97f8, `commit_count` was introduced to keep count of parsed commits for a repository.

Currently, it's used to assign `commit->index`. However, this behavior is incorrect, as the commit slab requires a global count instead of per-repo count. While a [patch](https://lore.kernel.org/git/20200612184014.1226972-2-abhishekkumar8222@gmail.com/) introduces the global counter, it does not clean up `commit_count`.

Remove `commit_count` and as it is no longer required for `alloc_commit_index()`, `init_commit_node()` and `object_as_type()` functions, stop passing them.

See the discussion at https://lore.kernel.org/git/xmqqpna40ws8.fsf@gitster.c.googlers.com/.

**Comment by raffs** [comment]
@abhishekkumar2718 it seems your changes `[6da43d9](https://github.com/gitgitgadget/git/commit/6da43d937ca96d277556fa92c5a664fb1cbcc8ac)` was merged to the `next` branch.  I believe this issue can be close.
