### ISSUE TITLE
'git log -p -D -S string' shows full patch of a deleted file ('-D' has no effect)

### ISSUE THREAD

**Issue by phil-blain** [gitgitgadget/git#800]

**Comment by adlternative** [comment]
Excuse me,this problem In my computer have not  appear.

The d.c have ‘Returns’.
I deleted d.c
I use 'git log -p -D' it show nothing.

I use 'git log -p -D -S Returns' it show nothing.
 
I use 'git log -p -S Returns' it show me the delete file context.

-D has its effort.

So this problem have been solved yet?

**Comment by phil-blain** [comment]
Indeed, it works correctly. 

What I was seeing is that when using an external diff program, then `-D` has no effect, this is a bit obvious in retrospect.

I was using my "pickaxe-diff" external diff, see #505.
