### ISSUE TITLE
Partial Clone: check `git log --follow` behavior

### ISSUE THREAD

**Issue by derrickstolee** [gitgitgadget/git#827]
This is mostly a note-to-self to check if this needs any work:

1. Create a blobless clone with `git clone --filter=blob:none`
2. Run `git log --follow -- <path>` for some `<path>` that has a rename, but only an _exact OID_ rename.
3. Check if that `git log --follow -- <path>` process downloads any blobs from the remote. (Optimally, it shouldn't.)

If there is no download, then perhaps reinforce that behavior with a test case.

If there _is_ a download, then this issue will serve as tracking to fix that problem.

**Comment by Abhra303** [comment]
Hello @derrickstolee  any update about the issue?

**Comment by derrickstolee** [comment]
I haven't looked at this in a while. Feel free to investigate, @Abhra303. This issue may not even be an issue, but could be a nice first contribution for either case (create a test or create a fix).

**Comment by Abhra303** [comment]
okay :)

**Comment by Abhra303** [comment]
Hi @derrickstolee,  I am having trouble to understand the "but only an exact OID rename." part you mentioned in the second point. Is this different from ordinary rename commits?

**Comment by derrickstolee** [comment]
If I rename a file without changing its contents, then the Git blob doesn't change, it still has the same hash. (See [this blog post about Git objects](https://github.blog/2020-12-17-commits-are-snapshots-not-diffs/) if you're unfamiliar.)

When `git log` is looking at a file, and it notices that the file was "added" by a commit (because the file does not exist in its parent), Git will look to see if any files were "deleted" (a file that exists in the parent, but not in the current commit). It then checks to see if the same blob OID appears as a delete and an add, in which case Git recognizes that as a rename. In particular, it is an "exact rename".

If there are adds and deletes but no exact renames detected, then Git will look at the contents of each file that was added and deleted to do a comparison between them. If two files are sufficiently close, then Git interprets that as an "inexact" rename (or a "rename-edit"). This second check is what would trigger blob downloads in a partial clone.

**Comment by Abhra303** [comment]
Marvellous info!! thank you so much for clearing my doubt :)

**Comment by Abhra303** [comment]
Hello @derrickstolee,

I am writing the test script for this test case and till now I didn't find a way to detect the downloading.
How can I detect if blobs are being downloaded? Could you tell me the approach of testing it?

I see the `git log --follow -- <path>` in both cases (exact OID and inexact rename) do not print any messages indicating the download (I observed the command runs slowly in the second case). So, I could not test the case by using `grep` functionality and checking the download related messages.

I also thought of using `git rev-list --objects --missing=print` command but as blob OID and blob contents are same (for both files) in "exact OID rename", I can't check if the blob of initial file is missing before running the command `git log --follow` and then check if the blob is downloaded.

Thanks :)

**Comment by Abhra303** [comment]
Thanks @derrickstolee , got it !

**Comment by Abhra303** [comment]
Created a PR #1175  regarding this ticket. Take a look at it when you're free :)

**Comment by Abhra303** [comment]
Should this be closed now?

**Comment by derrickstolee** [comment]
> Should this be closed now?

Absolutely! Thanks for the contribution, @Abhra303!
