### ISSUE TITLE
Segfault in git for-each-repo

### ISSUE THREAD

**Issue by buehmann** [gitgitgadget/git#833]
@derrickstolee, I was trying `git maintenance` earlier today and stumbled across the following bug after I had `git maintenance unregister`ed the last repo, which removed the `maintenance.repo` config.

```console
➜  bug (master) git --version
git version 2.30.0
➜  bug (master) git maintenance unregister
➜  bug (master) git config --global --get-all maintenance.repo; echo $?
1
➜  bug (master) git for-each-repo --config=maintenance.repo status # similar to what is run by the cron job
[1]    44380 segmentation fault  git for-each-repo --config=maintenance.repo status
```

https://github.com/gitgitgadget/git/blob/71ca53e8125e36efbda17293c50027d31681a41f/builtin/for-each-repo.c#L51-L54

**Comment by derrickstolee** [comment]
Thanks for bringing this to my attention. I'll get this fixed.

**Comment by buehmann** [comment]
Thanks!

**Comment by derrickstolee** [comment]
@buehmann could you please email me (my-alias at github dot com) with your preferred email so I can properly attribute you with a `Reported-by:` tag in my patch?

**Comment by buehmann** [comment]
I updated my profile: https://github.com/buehmann

**Comment by derrickstolee** [comment]
I'm closing this issue because #834 has landed in `next`. Thanks, @buehmann!
