### ISSUE TITLE
format-patch: pass --right-only to range-diff somehow

### ISSUE THREAD

**Issue by Denton-L** [gitgitgadget/git#876]
Since 1e79f97326 (range-diff: offer --left-only/--right-only options, 2021-02-05) is almost in `master`, it would be a good idea to teach `git format-patch` to pass `--right-only` to `range-diff`.

I (and [Taylor Blau](https://lore.kernel.org/git/YBx5rmVsg1LJhSKN@nand.local/)?) can't seem to reproduce the exact scenario right now but I've been in situations where running `git format-patch --range-diff --cover-letter` end up putting a bunch of new commits from upstream into the range-diff.

In the future when I'm free, I'll create a reproduction recipe for the issue stated above.

**Comment by dscho** [comment]
How about `git format-patch --range-diff=right-only`?

About reproducing the issue: it probably happens when you rebase to a new upstream commit between iterations.

**Comment by adlternative** [comment]
@Denton-L,@dscho, 
Passing a parameter is easy, maybe I don't think thoroughly, why do we just need right-only, don' t need left-only here?

**Comment by dscho** [comment]
The idea behind passing `--right-only` somehow is this: when you rebase a patch series, you might rebase it onto a newer version of, say, `next`. A `git range-diff` would now pretend that all of the new commits are super interesting, but they are not. Hence, one side of the range-diff will _always_ be more interesting than the other.

However, there is a problem here. That interesting direction would be `--left-only`, not `--right-only`.

Even worse: if we drop a patch from the patch series, and add a new one, both of those patches are interesting. Therefore, the `--left-only` option is dramatically less useful than I originally believed.

**Comment by adlternative** [comment]
> The idea behind passing `--right-only` somehow is this: when you rebase a patch series, you might rebase it onto a newer version of, say, `next`. A `git range-diff` would now pretend that all of the new commits are super interesting, but they are not. Hence, one side of the range-diff will _always_ be more interesting than the other.
> 
> However, there is a problem here. That interesting direction would be `--left-only`, not `--right-only`.
> 
> Even worse: if we drop a patch from the patch series, and add a new one, both of those patches are interesting. Therefore, the `--left-only` option is dramatically less useful than I originally believed.

@dscho, You're right. Recently, I have often thought about this problem, but found that `left-only` is not so good for user, because it always removes one side of the content.

**Comment by dscho** [comment]
Right. You might need a better heuristic, specifically addressing the scenario of patch series iterations.

I could imagine that a good indicator might be the committer: all the commits to be contributed are likely annotated with the current user as committer, and the commits they're based on likely have a different committer.

**Comment by adlternative** [comment]
> Right. You might need a better heuristic, specifically addressing the scenario of patch series iterations.
> 
> I could imagine that a good indicator might be the committer: all the commits to be contributed are likely annotated with the current user as committer, and the commits they're based on likely have a different committer.

@dscho ,
Thanks for this interesting idea! :)

I may have some little doubts:
As far as I know, the committer is the person who applies the patch 
and the author is the person who writes the patch. It may be suitable to 
rewrite a commit author which have been done with `git commit --author`, 
but I think it is a bit strange to rewrite a commit committer.

If I apply a patch base on other commiter's commit(s), 
shouldn't I be the this commit committer?

**Comment by dscho** [comment]
I did not suggest to _rewrite_ the commits, only to _look_ at them.

For example, assume that you sent three patches to the mailing list, A, B and C, and they're on top of `next`, where X is the tip of `next`:

```
- X - A - B - C
```

Then you're asked to rewrite A, drop B and add D, and rebase onto the _new_ tip of `next`, which is Y:

```
- X - Y - A' - C' - D
```

Note that X and Y have the maintainer as committer, A, B, C, A', C' and D have _you_ as committer.

Therefore, to figure out the commit ranges to feed to `git range-diff` when given only C and D would be to traverse the graph until a commit is found that does _not_ have you as committer: X and Y, respectively. The ranges would then be `X..C` and `Y..D`.

**Comment by adlternative** [comment]
> I did not suggest to _rewrite_ the commits, only to _look_ at them.
> 
Ok...I may have misunderstood your thoughts.
> For example, assume that you sent three patches to the mailing list, A, B and C, and they're on top of `next`, where X is the tip of `next`:
> 
> ```
> - X - A - B - C
> ```
> 
> Then you're asked to rewrite A, drop B and add D, and rebase onto the _new_ tip of `next`, which is Y:
> 
> ```
> - X - Y - A' - C' - D
> ```
> 
> Note that X and Y have the maintainer as committer, A, B, C, A', C' and D have _you_ as committer.
> 
> Therefore, to figure out the commit ranges to feed to `git range-diff` when given only C and D would be to traverse the graph until a commit is found that does _not_ have you as committer: X and Y, respectively. The ranges would then be `X..C` and `Y..D`.

Maybe you can indeed find the correct range this way, but what if the maintainer sends a patch?

**Comment by dscho** [comment]
Right, the maintainer would not be able to use this.

At the same time, this heuristic will fail substantially less often than the `--left-only` heuristic.

Therefore, I'd say it's better, even if the caveat needs to be spelled out clearly.

**Comment by Denton-L** [comment]
I think that if we have to rely on heuristics in order to make this feature work, it'll be too magical. It's easier to just keep it the old way.
