### ISSUE TITLE
format-patch: allow a non-integral (string??) version numbers

### ISSUE THREAD

**Issue by Denton-L** [gitgitgadget/git#882]
Sometimes, it may be helpful to send patches that aren't quite v1 or v2. Perhaps a small fixup on a patch should be labelled as v1.1. Teach git format-patch to accept string versions so that this is possible.

One thing to consider, when doing a range-diff, it will say "Changes since v1" or something. Perhaps we should change that to say "Changes since last version" or something when the version is not integral.

**Comment by adlternative** [comment]
Hey, Denton Liu,
I am interested in this issue and have made minor changes to the original code.
There's "# failed 41among remaining 180test (s)" in the "t4014-format-patch.sh", what can be done to locate the error for each test so I may be able to modify it.:)

**Comment by Denton-L** [comment]
Closed by #885.
